#!/usr/bin/env bash

echo "Creating database services..."
createdb services

echo "Running migration on postgres://expensly@192.168.59.103:5001/services?sslmode=disable&password=expensly..."
migrate -url postgres://expensly@192.168.59.103:5001/services?sslmode=disable\&password=expensly -path ./migrations up

echo "Creating database services-test"
createdb services-test

echo "Running migration on postgres://expensly@192.168.59.103:5001/services-test?sslmode=disable&password=expensly..."
migrate -url postgres://expensly@192.168.59.103:5001/services-test?sslmode=disable\&password=expensly -path ./migrations up